### ISSUE TITLE
is it possible to enable fuse-overlayfs with standard docker rootless

### ISSUE THREAD

**Issue by lukasheinrich** [AkihiroSuda/containerd-fuse-overlayfs#16]
I'm testing rootless docker (and podman) on CERN systems with the right system requirements for fuser-overlayfs. Is it possible to enable fuse-overlayfs with dockerd as shipped in the standard rootless docker install?

**Comment by AkihiroSuda** [comment]
Yes, already supported on Moby master (20.0X).

**Comment by AkihiroSuda** [comment]
https://github.com/moby/moby/pull/40483

**Comment by AkihiroSuda** [comment]
FYI master binaries are here
https://github.com/AkihiroSuda/moby-snapshot
