### ISSUE TITLE
can't find fuse3.fuse-overlayfs in ubuntu

### ISSUE THREAD

**Issue by liaohang122** [AkihiroSuda/containerd-fuse-overlayfs#19]
some code in file check.go：
m := mount.Mount{
		Type:    "fuse3." + fuseoverlayfsBinary,
		Source:  "overlay",
		Options: opts,
	}
the Type value is fuse3.fuse-overlayfs, execute unix.Mount , prompt "no such device"

System information:
Linux iZj6cgx3q19bmgalpqjydtZ 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

fuse-overlayfs --version:
  fuse-overlayfs: version 1.1.0
  FUSE library version 3.4.1
  using FUSE kernel interface version 7.27
  fusermount3 version: 3.9.0

**Comment by AkihiroSuda** [comment]
Does `fuse-overlayfs` CLI work? https://github.com/containers/fuse-overlayfs#usage

**Comment by AkihiroSuda** [comment]
Closing as outdated, but feel free to reopen
