### ISSUE TITLE
test fails. says I have do not have the device

### ISSUE THREAD

**Issue by Stephen-AI** [AkihiroSuda/containerd-fuse-overlayfs#4]
`$ go test -exec rootlesskit -test.v -test.root
=== RUN   TestFUSEOverlayFS
--- SKIP: TestFUSEOverlayFS (0.00s)
	fuseoverlayfs_test.go:49: fuse-overlayfs not supported: fuse-overlayfs not functional, make sure running with kernel >= 4.18: failed to mount fuse-overlayfs ({Type:fuse3.fuse-overlayfs Source:overlay Options:[lowerdir=/tmp/fuseoverlayfs-test022994873/fuseoverlayfs-check475343812/lower2:/tmp/fuseoverlayfs-test022994873/fuseoverlayfs-check475343812/lower1 writeback=0]}) on /tmp/fuseoverlayfs-test022994873/fuseoverlayfs-check475343812/merged: no such device
PASS
ok  	github.com/AkihiroSuda/containerd-fuse-overlayfs	0.022s
`
Maybe its because I have fuse but not fuse3, not sure how to get fuse3
`$ ls /dev | grep fuse
fuse
`
System information:
`$ uname -a
Linux stephen 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

Fuse Version:
`$ fuse-overlayfs --version
fuse-overlayfs: version 0.7
FUSE library version 3.8.0
using FUSE kernel interface version 7.31
`

**Comment by AkihiroSuda** [comment]
modprobe maybe

**Comment by Stephen-AI** [comment]
`$ modprobe fuse-overlayfs
modprobe: FATAL: Module fuse-overlayfs not found in directory /lib/modules/5.0.0-37-generic
`

**Comment by Stephen-AI** [comment]
`modprobe fuse` works but the result is still the same as before

**Comment by AkihiroSuda** [comment]
Does it work with root?

**Comment by Stephen-AI** [comment]
Do you mean running the test as root? If so I tried and I get.
`[rootlesskit:parent] error: failed to setup UID/GID map: failed to compute uid/gid map: No subuid ranges found for user "root"
exit status 1
FAIL	_/home/stephen/go/src/github.com/AkihiroSuda/containerd-fuse-overlayfs	0.005s
`

**Comment by AkihiroSuda** [comment]
`go test -exec sudo -test.v -test.root`

**Comment by AkihiroSuda** [comment]
`mknod -m 666 c /dev/fuse 10 229` may work

**Comment by Stephen-AI** [comment]
I get `$ sudo mknod -m 0666 c /dev/fuse 10 229 
mknod: invalid device type ‘/dev/fuse’
`

**Comment by AkihiroSuda** [comment]
`mknod -m 666 /dev/fuse c 10 229`

**Comment by Stephen-AI** [comment]
That went throught but it says `mknod: /dev/fuse: File exists
`

**Comment by AkihiroSuda** [comment]
`make test`

**Comment by AkihiroSuda** [comment]
If it doesn't work, maybe you need Ubuntu 19.10

**Comment by Stephen-AI** [comment]
Oh I see. I'll get a team mate to run the test on his ubuntu 19.10. Thank you for your help

**Comment by Stephen-AI** [comment]
`sudo make test
DOCKER_BUILDKIT=1 docker build -t containerd-fuse-overlayfs-test .
[+] Building 2.2s (8/31)                                                                                                                                                   
 => [internal] load .dockerignore                                                                                                                                     0.2s
 => => transferring context: 34B                                                                                                                                      0.0s
 => [internal] load build definition from Dockerfile                                                                                                                  0.1s
 => => transferring dockerfile: 38B                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/alpine:3.10                                                                                                        1.0s
 => [internal] load metadata for registry.fedoraproject.org/fedora:30                                                                                                 0.6s
 => [internal] load metadata for docker.io/library/golang:1.13-alpine                                                                                                 1.0s
 => [fuse-overlayfs 1/6] FROM registry.fedoraproject.org/fedora:30@sha256:89f64521a1b662ab3ba9c7f73f66b007a8eab65f403c1647a9a9b2238521ad4a                            0.9s
 => => resolve registry.fedoraproject.org/fedora:30@sha256:89f64521a1b662ab3ba9c7f73f66b007a8eab65f403c1647a9a9b2238521ad4a                                           0.0s
 => => sha256:89f64521a1b662ab3ba9c7f73f66b007a8eab65f403c1647a9a9b2238521ad4a 1.22kB / 1.22kB                                                                        0.0s
 => => sha256:6a42679df586fff6865fd9028b21e396c678822b47629c188746869fa7533a36 429B / 429B                                                                            0.0s
 => => sha256:54753be8e9cb3d20c4c9eaac2ca29fc10cdd32abd7b865666f8a192cbb960ff7 1.32kB / 1.32kB                                                                        0.0s
 => => sha256:28b2392cb059c33939681ba615ee85378f983948c2f64b17f458d2e3185a32be 5.19MB / 77.37MB                                                                       0.8s
 => [containerd-fuse-overlayfs-test 1/3] FROM docker.io/library/golang:1.13-alpine@sha256:52a0918d146489349933a9202cca3455d1a37ecc81825fa99f96e9ba625bbd51            0.9s
 => => resolve docker.io/library/golang:1.13-alpine@sha256:52a0918d146489349933a9202cca3455d1a37ecc81825fa99f96e9ba625bbd51                                           0.0s
 => => sha256:ddf407284440a94889dc139bbe1be1daa19d99e166d6b1f2dfc6919846810b4e 1.36kB / 1.36kB                                                                        0.0s
 => => sha256:69cf534c966ad5603c79677824b62d50406ee3d3ef22d49640be95853c195476 3.81kB / 3.81kB                                                                        0.0s
 => => sha256:8ef94372a977c02d425f12c8cbda5416e372b7a869a6c2b20342c589dba3eae5 301.72kB / 301.72kB                                                                    0.0s
 => => sha256:1ec62c064901392a6722bb47a377c01a381f4482b1ce094b6d28682b6b6279fd 155B / 155B                                                                            0.0s
 => => sha256:339073ee4259ec00139ce0f376829e2c265f67aabe406e82cb6e2ee559ea1ea6 4.20MB / 126.88MB                                                                      0.8s
 => => sha256:df12825c8c18ed0861e6dda82b3c9cdca4c00b65d57e6d04f67d3e198fab3a06 125B / 125B                                                                            0.0s
 => => sha256:52a0918d146489349933a9202cca3455d1a37ecc81825fa99f96e9ba625bbd51 1.65kB / 1.65kB                                                                        0.0s
 => [internal] load build context                                                                                                                                     0.2s
 => => transferring context: 65.78kB                                                                                                                                  0.1s
 => CACHED [stage-4 1/7] FROM docker.io/library/alpine:3.10@sha256:c19173c5ada610a5989151111163d28a67368362762534d8a8121ce95cf2bd5a                                   0.0s
 => CACHED [internal] helper image for file operations                                                                                                                0.0s
 => [idmap 2/5] RUN apk add --no-cache autoconf automake build-base byacc gettext gettext-dev gcc git libcap-dev libtool libxslt                                      0.9s
unexpected EOF
`

**Comment by AkihiroSuda** [comment]
Is this still an issue?
